name: Deploy to Vimexx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /domains/origyns.nl/public_html/jail/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**